### ISSUE TITLE
self.data_dir in the function evaluate()

### ISSUE THREAD

**Issue by russab0** [voidful/BDG#2]
Hello!
It seems like there is a typo in the code. Here is a snippet from the function evaluate():
`with open(args.data_dir, "r", encoding='utf8') as f:
        inputjson = [json.loads(jline) for jline in f.readlines()]`

But args.data_dir(), as its name suggests is not a file that can be opened, but a directory. Probably you wanted to use some other variable here. Could you please clarify this moment?
Thank you in advance!

**Comment by voidful** [comment]
original run_multiple_choice.py takes directory as input.
I modify it for reading jsonl format file instead of reading a specific file inside a folder.

Rather than changing all the arguments, I use a shortcut that changing the Race dataset get_test_examples behavior to achieve this. 

https://github.com/voidful/BDG/blob/1e8112bfecf2af37183c176145141cac10079983/transformers/examples/utils_multiple_choice.py#L106

**Comment by russab0** [comment]
I am sorry, but I do not see the relation between the function _evaluate_ (which I was talking about) and the method _get_test_examples_ (which you are referring to). Lines `with open(args.data_dir, "r", encoding='utf8') as f: inputjson = [json.loads(jline) for jline in f.readlines()]` do not call neither _get_test_examples_() nor _load_and_cache_examples_().

The problem is that I want to run _main_() with do_train==do_eval==do_test==True, but that do no work with just single argument _args.data_dir_ since _open_() requires a file, but _get_test_examples_() and _get_test_examples_() require a directory.
Can I ask you to investigate the issue?

**Comment by voidful** [comment]
My modification here only works for do_train==do_eval in the same time. I modify do_test for entropy selection in BDG. 
If you want to run run main() with do_train==do_eval==do_test in, I suggest to use https://github.com/huggingface/transformers/tree/master/examples/multiple-choice
